### ISSUE TITLE
Add BetterShard messages

### ISSUE THREAD

**Issue by Maxopoly** [TealNerd/CivGuide#10]
When someone uses a portal for the first time, explain roughly how it works.

**Comment by TealNerd** [comment]
Yeah I need to add that I guess, I don't really know anything about how bettershards works if someone else wants to add it it's pretty simple

**Comment by Maxopoly** [comment]
Just listen for that : https://github.com/Civcraft/BetterShards/blob/master/src/vg/civcraft/mc/bettershards/events/PlayerChangeServerEvent.java
