### ISSUE TITLE
Replace PlayerItemHeldEvent

### ISSUE THREAD

**Issue by Maxopoly** [TealNerd/CivGuide#4]
You are using PlayerItemHeldEvent for most of the stuff, but that's not ideal in my opinion, because people will rarely put the stuff they pickup on their hotbar right away and select it. I would recommend to replace it with PlayerItemPickUp and InventoryClickEvent, which both use the same message, so for example whenever a player obtains a pearl he gets the messages instead of when he puts it in his hand.

**Comment by TealNerd** [comment]
Sadly there is no ItemPickupEvent, I'll look at the click event though that could be better

**Comment by Maxopoly** [comment]
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerPickupItemEvent.html

?
